### ISSUE TITLE
Suggestions for documentation clarifications

### ISSUE THREAD

**Issue by fmahebert** [UIUC-PPL/charm#3139]
Over the past few months, @moxcodes and I have been working to add load balancing and checkpoint/restart in SpECTRE.

Here's a list of some things we've encountered in the Charm++ documentation that we felt could be clarified, as well as some questions that we thought would be useful to have addressed by the documentation. This list is a bit lengthy, so we've done our best to organize it by section and break it up into smaller items that can be checked off.

We're happy to discuss any items where we haven't made ourselves/our questions clear!

Based on Charm++ v6.11.0-beta1, and documentation from https://charm.readthedocs.io/en/latest/index.html as of late Oct 2020.

---

2.2.6 - Load Balancing

2.2.6.1

- [x] First sentence: our understanding is that singletons cannot migrate either, in which case the statement should be restricted to array chares only.

- [x] Are LB measurements done for every charm application, or only in cases where the user "turns on" LB by linking in a LB module or calling charm functions or using command-line args? If one of the latter, which?

- [x] Can the documentation state (here or in a different section, if more appropriate) when LB measurements start? Do measurements start as soon as the application starts up, or later? In other words, will startup costs enter into the LB decision on the first LB invocation? Does the answer depend on whether periodic, at sync, or manual LB is used?

- [x] Does the load balancing database get reset after a LB invocation? Does this depend on whether any chares are actually migrated by the LB?

2.2.6.2

- [x] Since v6.11 will be gathering several LBs under TreeLB and eliminating other LBs, it would help discoverability and usability if the documentation were updated to provide an accurate listing of available LBs. Specific concerns:

  1) [x] [Already in #3131] Given that many LBs are implemented within TreeLB, it would be nice to improve their discoverability. Ideally these sub-balancers would once again appear in the output from running `exec +balancer help`, but providing a detailed listing of the sub-balancers implemented by TreeLB in the main documentation would also be very helpful. This information would be useful not just for running in "legacy" mode, but also for setting up the TreeLB config file.

  2) [x] Relatedly, since TreeLB exposes the ability to configure the individual LB strategies, it would be helpful to document the parameters for each of the strategies. Ideally, these would be listed in the documentation but also in the command-line help text so that if the documentation isn't updated, at least the command line utility can report details of the current branch of the code.

  3) [x] The documentation lists some LBs that appear to have been removed, e.g., TopoCentLB. We suggest removing from this listing any LBs that are not actually available.

  4) [x] The documentation uses phrases like
     > Listed below are some of the available non-trivial...
     > Listed below are some of the communication-aware load balancers;

      which imply the existence of even more LBs. It would be helpful —and perhaps easier now that 6.11 has fewer LBs?— to ensure all LBs are listed in the documentation.

- [x] There are numerous mentions of the SCOTCH load-balancer. Is it still available? If it is still supported, it would be very helpful if more detailed build instructions could be provided for it, especially in light of #3136.

- [x] It would be helpful to note the existence of the LIBS and/or everylb build targets, and specify which LBs are only built through these targets.

- [x] What is the format for a Metabalancer model? The gzips provided in `charm/src/ck-ldb/rf_model` are both long ascii files of numeric parameters, so don't help a user in understanding what the models are or how to train one for their own purposes.

2.2.6.3

- [x] The sentence
  > However, in one scenario, those automatic load balancers will fail to work - when array elements are created by dynamic insertion.

    implies to us that dynamic insertion and LB cannot be used in the same application. But we understand this is actually okay, as long as they occur at different times and using `doneInserting` to indicate insertions are finished. This is mentioned in "2.3.4.2.5. Dynamic Insertion". Can the main LB documentation clarify this behavior?

- [x] Can an application dynamically insert several elements, call `doneInserting`, run for a significant period of time while load balancing, but then insert new elements? If this is possible, then followup clarifications:

  1) [x] Is there an additional call that is required to notify the charm runtime that insertion will resume? For example, is it necessary to wrap the dynamic insertion events with `TurnManualLBOn` and `TurnManualLBOff`?

  2) [x] Is this compatible with periodic or at sync load balancing? Is this process acceptable if it can be assured that no element calls `AtSync` while any elements are being inserted?

subsection "2. At sync mode"

- [x] The at sync documentation says
  > When all local elements call AtSync the load balancer is triggered

    Is it the case that if only a subset of the elements on a core call `AtSync`, those elements will wait indefinitely for the rest of the elements on the same core to also call `AtSync`?

- [x] If an application has multiple chare arrays, and `usesAtSync` is set to true in the elements of one array only, what happens? Will that one chare array use at sync LB while the others use periodic LB?

- [x] The at sync documentation notes that
  > the minimum time for a AtSync() load balancing to occur is controlled by the LBPeriod

    Can the documentation clarify how `AtSync` and `+LBPeriod` interact? E.g., if the elements call `AtSync` but a full LBPeriod has not elapsed since the last `AtSync` call, does the runtime wait until the LBPeriod clock is ready and then invoke the LB? or does the runtime skip LB and go straight to `ResumeFromSync`?

subsection "3. Manual mode"

- [x] In manual mode, how are the measurements for the LB database gathered? Are the measurements automatic, or are they manually started by `TurnManualLBOn` or by `CkStartLB`?

- [x] After calling `CkStartLB`, how do we know if/when load balancing is done? or is it just perpetual? It would be nice to clarify whether this does "one iteration" of LB, or continuous LB as controlled by `+LBPeriod` until `TurnManualLBOff` is called.

- [x] Is there some way to specify a callback to invoke after `CkStartLB` load balancing is complete?

2.2.6.6
subsection 2. Building individual load balancers

- [x] [Already in #3136] This section advertises a way of building individual LBs, that does not work on v6.11.0-beta1. Delete this section?

2.3.12 - Checkpoint/Restart-Based Fault Tolerance

- [x] How does the initialization sequence given [here](https://charm.readthedocs.io/en/latest/charm++/manual.html?highlight=ckentryoption#initializations-at-program-startup) change when restarting from a checkpoint? Do the different types of chares still get initialized in the order (mainchare -> group/nodegroup chares -> array chares)? Are dependencies (as specified when starting up from the mainchare's `CkArgMsg` constructor) between groups/nodegroups maintained in a restart from checkpoint? It would be helpful to clarify these questions in either the initialization or the checkpoint/restart documentation... even if just to say the behavior is unknown or undefined.

- [x] How do readonly variables interact with checkpoint/restarting? Are they automatically saved and restored? Should they be pup'd by the mainchare? Or should the value be reassigned in the `CkMigrateMessage` mainchare constructor, mirroring how they are assigned in the first program startup?

- [x] If a chare holds a CProxy as a member variable, how does this member variable interact with checkpoint/restart? Is the CProxy after the restart immediately in a valid state (though all the array elements the proxy may "contain" aren't yet) or do we need to somehow set the CProxy after restart? If we need to set the CProxy after restart, how do we do that since nothing can communicate without the CProxy's being set?

**Comment by fmahebert** [comment]
Pinging @moxcodes and @nilsdeppe to follow along
